=== LJJimChen/UI-For-UWP-Demos/QSF.UWP/ExamplesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 rel. 2 (http://www.altova.com) by tbb (office) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Root">
		<xs:annotation>
			<xs:documentation>Root Element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="HomepageInfo">
					<xs:complexType>
						<xs:sequence>
							<xs:sequence>
								<xs:element name="Headline" maxOccurs="2">
									<xs:complexType>
										<xs:attribute name="text" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:element name="Highlights">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Highlight" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="WhatsNew" minOccurs="0">
								<xs:annotation>
									<xs:documentation>only in SL</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Highlight" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Controls">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Control" maxOccurs="unbounded">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="ControlType"/>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="ControlName">
						<xs:selector xpath="Control"/>
						<xs:field xpath="@name"/>
					</xs:unique>
				</xs:element>
				<xs:element name="HighlightedControls">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="HighlightedControl" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="platform" type="PlatformType"/>
                </xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
        <xs:element name="HighlightedExamples">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="HighlightedExample" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:complexContent>
                    <xs:extension base="Highlight" />
                  </xs:complexContent>
                  <xs:attribute name="name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="HighlightedApps">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="HighlightedApp" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="Highlight" minOccurs="0" maxOccurs="unbounded"/>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="thumbnail" type="xs:string" use="required"/>
                  <xs:attribute name="icon" type="xs:string" use="optional"/>
                  <xs:attribute name="shortDescription" type="xs:string" use="required"/>
                  <xs:attribute name="detailedDescription" type="xs:string" use="required"/>
                  <xs:attribute name="link" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="ControlKey">
			<xs:selector xpath="Controls/Control"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:keyref name="HighlightedControlKeyRef" refer="ControlKey">
			<xs:selector xpath="HighlightedControls/HighlightedControl"/>
			<xs:field xpath="@name"/>
		</xs:keyref>
	</xs:element>
	<xs:complexType name="ControlType">
		<xs:annotation>
			<xs:documentation>Element describes the control type</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Group" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Example" maxOccurs="unbounded">
							<xs:complexType>
                <xs:sequence>
                  <xs:element name="Highlight" maxOccurs="unbounded" minOccurs="0"/>
                </xs:sequence>
								<xs:attribute name="name" type="xs:string" use="required"/>
								<xs:attribute name="text" type="xs:string" use="required"/>
								<xs:attribute name="description" type="xs:string" use="optional"/>
								<xs:attribute name="commonFolders" type="xs:string" use="required"/>
								<xs:attribute name="keywords" use="required"/>
								<xs:attribute name="isDefault" type="xs:boolean"/>
								<xs:attribute name="packageName"/>
								<xs:attribute name="status" type="ExampleStatusType"/>
								<xs:attribute name="type" type="ExampleType"/>
								<xs:attribute name="headerText" type="xs:string" use="required"/>
								<xs:attribute name="canPinToDesktop" type="xs:boolean" />
								<xs:attribute name="platform" type="PlatformType"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="keywords" type="xs:string"/>
		<xs:attribute name="text" type="xs:string" use="optional"/>
		<xs:attribute name="status" type="ExampleStatusType" use="optional"/>
		<xs:attribute name="description" type="xs:string"/>
		<xs:attribute name="platform" type="PlatformType"/>
	</xs:complexType>
	<xs:element name="Highlight">
		<xs:annotation>
			<xs:documentation>No need for subtitles - not used</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="text" type="xs:string" use="optional"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
			<xs:attribute name="image" type="xs:string" use="optional"/>
      <xs:attribute name="widthMultiplier" type="xs:string" use="optional"/>
      <xs:attribute name="heightMultiplier" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="ExampleStatusType">
		<xs:annotation>
			<xs:documentation>Element describes the example status type - new, beta, etc.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Normal"/>
			<xs:enumeration value="New"/>
			<xs:enumeration value="Beta"/>
			<xs:enumeration value="CTP"/>
			<xs:enumeration value="Updated"/>
			<xs:enumeration value="Obsolete"/>
      <xs:enumeration value="Universal"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ExampleType">
		<xs:annotation>
			<xs:documentation>Element describes the example type - normal or theming example</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Normal"/>
			<xs:enumeration value="Theming"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PlatformType">
		<xs:annotation>
			<xs:documentation>Element describes the platform of the control - UWP or WindowsUniversal</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="UWP"/>
			<xs:enumeration value="WindowsUniversal"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== LJJimChen/UI-For-UWP-Demos/QSF.UWP/Examples.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ExamplesSchema.xsd">
  <HomepageInfo>
    <Headline text="This is Headline 1" />
    <Highlights>
      <Highlight description="Highlight 1 description" image="/Application;component/Resources/Images/Highlights1.png" text="Highlight 1 text" />
      <Highlight description="Highlight 2 description" image="/Application;component/Resources/Images/Highlights2.png" text="Highlight 2 text" />
    </Highlights>
    <WhatsNew>
      <Highlight image="/QSF/Assets/Whatsnew/Whatsnew1.png" text="Whatsnew 1 text" description="Whatsnew 1 description" />
      <Highlight image="/QSF/Assets/Whatsnew/Whatsnew2.png" text="Whatsnew 2 text" description="Whatsnew 2 description" />
    </WhatsNew>
  </HomepageInfo>
  <Controls>
    <Control name="Chart" keywords="chart" description="Light-weight and super-fast charting component for your Windows Universal applications." text="Chart">
      <Group name="Overview">
        <Example name="Chart.FirstLook.Example" isDefault="true" headerText="Sales dashboard" commonFolders="Chart/FirstLook" keywords="chart" text="First Look">
          <Highlight widthMultiplier="4" heightMultiplier="4" image="Chart/Assets/Highlights/chart_salesdashboard_310x330.jpg" />
        </Example>
      </Group>
      <Group name="Gallery">
        <Example name="Chart.Gallery.Bar.FirstLook" commonFolders="Chart/Gallery/" keywords="chart, gallery, bar" text="Gallery" headerText="Bar series" />
        <Example name="Chart.Gallery.Line.FirstLook" commonFolders="Chart/Gallery" keywords="chart, gallery, line" text="Gallery" headerText="Line series" />
        <Example name="Chart.Gallery.Area.FirstLook" commonFolders="Chart/Gallery" keywords="chart, gallery, area" text="Gallery" headerText="Area series" />
        <Example name="Chart.Gallery.Step.FirstLook" commonFolders="Chart/Gallery/" keywords="chart, gallery, step" text="Gallery" headerText="Step series" />
        <Example name="Chart.Gallery.Range.FirstLook" commonFolders="Chart/Gallery/" keywords="chart, gallery, range" text="Gallery" headerText="Range series" />
        <Example name="Chart.Gallery.Point.FirstLook" commonFolders="Chart/Gallery/" keywords="chart, gallery, point" text="Gallery" headerText="Point series" />
        <Example name="Chart.Gallery.Scatter.FirstLook" commonFolders="Chart/Gallery" keywords="chart, gallery, scatter" text="Gallery" headerText="Scatter series" />
        <Example name="Chart.Gallery.Pie.FirstLook" commonFolders="Chart/Gallery" keywords="chart, gallery, pie" text="Gallery" headerText="Pie series" />
        <Example name="Chart.Gallery.Doughnut.FirstLook" commonFolders="Chart/Gallery" keywords="chart, gallery, doughnut" text="Gallery" headerText="Doughnut series" />
        <Example name="Chart.Gallery.Financial.FirstLook" commonFolders="Chart/Gallery" keywords="chart, gallery, stock, financial" text="Gallery" headerText="Financial series" />
        <Example name="Chart.Gallery.Radar.FirstLook" commonFolders="Chart/Gallery" keywords="chart, gallery, radar" text="Gallery" headerText="Radar series" />
        <Example name="Chart.Gallery.Polar.FirstLook" commonFolders="Chart/Gallery" keywords="chart, gallery, polar" text="Gallery" headerText="Polar series" />
      </Group>
      <Group name="Financial">
        <Example name="Chart.Stock.StockSeries" platform="WindowsUniversal" commonFolders="Chart/Financial" keywords="chart, Financial" text="Stock series and indicators" headerText="Stock series/indicators">
          <Highlight widthMultiplier="2" heightMultiplier="2" image="Chart/Assets/Highlights/chart_stockseries_150x160.jpg" />
        </Example>
      </Group>
      <Group name="Annotations">
        <Example name="Chart.Annotations.Example" commonFolders="Chart/Annotations" keywords="chart, Annotations" text="Annotations" headerText="Annotations">
          <Highlight widthMultiplier="6" heightMultiplier="6" image="Chart/Assets/Highlights/chart_annotations_470x500.jpg" />
        </Example>
      </Group>
      <Group name="Multiple Axes">
        <Example name="Chart.MultipleAxes.Example" commonFolders="Chart/MultipleAxes" keywords="chart, Multiple Axes" text=" Multiple Axes" headerText=" Multiple Axes">
          <Highlight widthMultiplier="2" heightMultiplier="2" image="Chart/Assets/Highlights/chart_multipleaxes_150x160.jpg" />
        </Example>
      </Group>
      <Group name="Interactivity">
        <Example name="Chart.Interactivity.Example" commonFolders="Chart/Interactivity" keywords="chart, Interactivity, scrolling, zoom, pan" text="Interactivity" headerText="Interactivity" />
      </Group>
      <Group name="Empty Values">
        <Example name="Chart.EmptyValues.Example" commonFolders="Chart/EmptyValues" keywords="chart, EmptyValues, scrolling, zoom, pan" text="Empty Values" headerText="Empty Values">
          <Highlight widthMultiplier="2" heightMultiplier="2" image="Chart/Assets/Highlights/chart_emptyvalues_150x160.jpg" />
        </Example>
      </Group>
      <Group name="Burndown Chart">
        <Example name="Chart.BurndownChart.Example" commonFolders="Chart/BurndownChart" keywords="chart, BurndownChart, annotations" text="Burndown Chart" headerText="Burndown Chart"/>
      </Group>
    </Control>
    <Control name="Gauge" keywords="gauge" description="A gauge control for visualizing and highlighting some data indicators." text="Gauge">
      <Group name="Overview">
        <Example headerText="Radial/Linear" name="Gauge.Gallery.FirstLook" isDefault="true" commonFolders="Gauge/Gallery" keywords="gauge" text="First Look">
          <Highlight widthMultiplier="6" heightMultiplier="6" image="Gauge/Assets/Highlights/gauge_464x494.png" />
        </Example>
      </Group>
    </Control>
    <Control name="BulletGraph" keywords="bulletgraph" description="RadBulletGraph is a data visualization component that clearly and concisely describes a single datum compared to one or two additional data." text="Bullet Graph">
      <Group name="Overview">
        <Example headerText="First look" name="BulletGraph.FirstLook.Example" isDefault="true" commonFolders="BulletGraph/FirstLook" keywords="bulletgraph" text="First Look">
          <Highlight widthMultiplier="6" heightMultiplier="6" image="BulletGraph/Assets/Highlights/bulletgraph_464x494.png" />
        </Example>
      </Group>
    </Control>
    <Control name="DatePicker" keywords="date, picker, datepicker" description="RadDatePicker is a control that allows the user to select a date from a popup selector through a intuitive user experience." text="Date Picker">
      <Group name="Overview">
        <Example headerText="First Look" name="DatePicker.FirstLook.Example" isDefault="true" commonFolders="DatePicker/FirstLook" keywords="date, picker, datepicker" text="First Look" />
      </Group>
      <Group name="Features">
        <Example headerText="Inline selector" name="DatePicker.DisplayMode.Example" isDefault="true" commonFolders="DatePicker/DisplayMode" keywords="date, picker, datepicker" text="Display Mode">
          <Highlight widthMultiplier="6" heightMultiplier="6" image="DatePicker/Assets/Highlights/datepicker_470x500.jpg" />
        </Example>
      </Group>
    </Control>
    <Control name="ListView" keywords="listview, list" description="RadListView is a control" text="ListView">
      <Group name="Overview">
        <!--<Example headerText="Horizontal Layout" name="ListView.HorizontalLayout.Example" isDefault="false" commonFolders="ListView/HorizontalLayout" keywords="listview, list" text="Horizontal Layout" />-->
        <Example headerText="Reorder" name="ListView.Reorder.Example" isDefault="true" commonFolders="ListView/Reorder" keywords="listview, list" text="Reorder">
          <Highlight widthMultiplier="4" heightMultiplier="4" image="ListView/Assets/Highlights/ListView-Reorder.png" />
        </Example>
      </Group>
    </Control>
    <Control name="TimePicker" keywords="time, picker, timepicker" description="RadTimePicker is a control that allows for selecting a time from a popup selector through a intuitive user experience." text="Time Picker">
      <Group name="Overview">
        <Example headerText="First Look" name="TimePicker.FirstLook.Example" isDefault="true" commonFolders="TimePicker/FirstLook" keywords="time, picker, timepicker" text="First Look">
          <Highlight widthMultiplier="6" heightMultiplier="6" image="TimePicker/Assets/Highlights/timepicker_464x494.png" />
        </Example>
      </Group>
    </Control>
    <Control name="HubTile" keywords="tile, hubtile" description="The Telerik hub tile controls, also called live tiles, mimic the behavior of the native User Experience found in the home screen of Windows Universal. These are rectangular UI elements that dynamically update themselves to show the latest and up to date information from different services or app functionality." text="Hub Tile">
      <Group name="Overview">
        <Example headerText="First Look" name="HubTile.FirstLook.Example" isDefault="true" commonFolders="HubTile/FirstLook" keywords="tile, hubtile" text="First Look">
          <Highlight widthMultiplier="6" heightMultiplier="6" image="HubTile/Assets/Highlights/hubtile_470x500.jpg" />
        </Example>
        <Example headerText="Gallery" name="HubTile.Gallery.Example" commonFolders="HubTile/Gallery" keywords="tile, hubtile, gallery" text="Gallery" />
      </Group>
    </Control>
    <Control name="HexView" keywords="tile, itemscontrol,hexview" description="TODO" text="Hex View">
      <Group name="Overview">
        <Example headerText="First Look" name="HexView.FirstLook.Example" isDefault="true" commonFolders="HexView/FirstLook" keywords="tile, hexview" text="First Look">
          <!--<Highlight widthMultiplier="6" heightMultiplier="6" image="HubTile/Assets/Highlights/hubtile_470x500.jpg" />-->
        </Example>
      </Group>
    </Control>
